export const COMPOSTING_METHODS = [
  {
    id: "hot_composting",
    name: "Hot Composting",
    type: "hot" as const,
    timeToFinish: "4-8 weeks",
    spaceNeeded: "3x3x3 ft minimum (1 cubic yard)",
    materials: ["Kitchen scraps (greens)", "Dry leaves or straw (browns)", "Grass clippings", "Coffee grounds", "Cardboard (shredded)"],
    steps: [
      "Build pile in layers: 4\" browns, 2\" greens, repeat until 3ft tall",
      "Water each layer until damp like a wrung-out sponge",
      "Monitor temperature — should reach 130-150°F within 3-5 days",
      "Turn when temperature drops below 110°F (every 3-7 days)",
      "Pile should heat up again after turning — if not, add nitrogen (greens)",
      "Finished when pile no longer heats up and material is dark, crumbly, earthy-smelling",
    ],
    troubleshooting: [
      { problem: "Pile won't heat up", cause: "Not enough nitrogen (greens) or too dry", fix: "Add fresh grass clippings or kitchen scraps. Water until damp." },
      { problem: "Pile smells bad", cause: "Too wet or too much nitrogen", fix: "Add browns (dry leaves, cardboard). Turn to aerate." },
      { problem: "Pile attracts flies", cause: "Food scraps exposed on surface", fix: "Always bury food scraps under 4\" of browns." },
      { problem: "Pile is slimy", cause: "Anaerobic conditions — too wet, too compacted", fix: "Turn thoroughly. Add coarse browns for air pockets." },
    ],
    nriTip: "Hot composting is the fastest path to finished compost. The key is mass — you need enough material to insulate the core. Start saving browns in fall for spring pile-building.",
  },
  {
    id: "cold_composting",
    name: "Cold / Passive Pile",
    type: "cold" as const,
    timeToFinish: "6-12 months",
    spaceNeeded: "Any size — even a corner of the yard",
    materials: ["Kitchen scraps", "Yard waste", "Leaves", "Small prunings", "Coffee grounds"],
    steps: [
      "Find a spot in your yard — shaded is fine",
      "Add materials as you generate them — no layering required",
      "Roughly alternate greens and browns when you remember",
      "Walk away. Let time and biology do the work",
      "Harvest finished compost from the bottom after 6-12 months",
    ],
    troubleshooting: [
      { problem: "Takes too long", cause: "Normal — cold composting is slow by design", fix: "If you want speed, switch to hot composting. Otherwise, patience is the method." },
      { problem: "Animals getting into pile", cause: "Meat, dairy, or oils in the pile", fix: "Remove attractants. Use a wire mesh enclosure." },
    ],
    nriTip: "Cold composting is the easiest method. It requires almost no effort — just keep adding material. Perfect for people who want compost but don't want a project.",
  },
  {
    id: "vermicomposting",
    name: "Vermicomposting (Worm Bin)",
    type: "vermi" as const,
    timeToFinish: "3-4 months per batch",
    spaceNeeded: "2x1x1 ft bin — fits under a sink or in a closet",
    materials: ["Red wiggler worms (Eisenia fetida)", "Shredded newspaper or cardboard (bedding)", "Kitchen scraps (no citrus, onion, or meat)"],
    steps: [
      "Set up bin with 4-6\" of moist shredded newspaper as bedding",
      "Add 1 lb of red wigglers (about 1000 worms)",
      "Feed 1 lb of food scraps per week per pound of worms",
      "Bury food in different spots each feeding — rotate around the bin",
      "Harvest castings every 3-4 months by moving finished material to one side and feeding only the other",
      "Use castings as top-dress or mix into potting soil at 10-20%",
    ],
    troubleshooting: [
      { problem: "Worms trying to escape", cause: "Bin too acidic, too wet, or too hot", fix: "Add dry bedding. Check for rotting food. Move to cooler spot." },
      { problem: "Fruit flies", cause: "Food exposed on surface", fix: "Always bury food under bedding. Freeze scraps before adding to kill fly eggs." },
      { problem: "Bad smell", cause: "Overfeeding or poor drainage", fix: "Stop feeding for a week. Add bedding. Ensure bin has drainage holes." },
    ],
    nriTip: "Worm castings are the richest compost you can make. A small bin processes all your kitchen scraps year-round. Perfect for apartment gardeners.",
  },
  {
    id: "bokashi",
    name: "Bokashi Fermentation",
    type: "bokashi" as const,
    timeToFinish: "2 weeks fermentation + 2-4 weeks soil burial",
    spaceNeeded: "5-gallon bucket with lid",
    materials: ["Bokashi bran (inoculated with EM microbes)", "All kitchen scraps including meat and dairy", "Airtight bucket with spigot"],
    steps: [
      "Add food scraps to bucket in 2\" layers",
      "Sprinkle handful of bokashi bran on each layer",
      "Press down firmly to remove air",
      "Seal lid tightly — this is anaerobic fermentation",
      "Drain liquid every 2-3 days (dilute 100:1 for plant fertilizer)",
      "After 2 weeks, bury fermented material in garden trench 12\" deep",
      "Wait 2-4 weeks before planting in that spot",
    ],
    troubleshooting: [
      { problem: "Bucket smells putrid (not sweet-sour)", cause: "Air getting in or not enough bran", fix: "Add more bran. Press contents down. Ensure airtight seal." },
      { problem: "White mold on surface", cause: "Normal — this is beneficial fungi", fix: "No action needed. White mold is a good sign." },
      { problem: "Blue/green mold", cause: "Contamination from air exposure", fix: "Remove affected material. Add extra bran. Seal more tightly." },
    ],
    nriTip: "Bokashi handles everything including meat and dairy — the only method that does. It's fermentation, not decomposition, so it works in any climate, any season.",
  },
  {
    id: "trench_composting",
    name: "Trench Composting",
    type: "trench" as const,
    timeToFinish: "1-3 months in-ground",
    spaceNeeded: "Any garden bed with space between rows or between seasons",
    materials: ["Kitchen scraps", "Shovel", "That's it"],
    steps: [
      "Dig a trench 12\" deep between garden rows or in a fallow bed",
      "Add kitchen scraps to the trench — 4-6\" deep",
      "Cover with the excavated soil",
      "Walk away. Worms and microbes process it underground",
      "Plant in that spot next season — the soil will be enriched",
    ],
    troubleshooting: [
      { problem: "Animals digging up scraps", cause: "Not buried deep enough", fix: "Bury at least 12\" deep. Tamp soil firmly." },
      { problem: "Plants near trench wilting", cause: "Fresh material too close to roots, pulling nitrogen", fix: "Keep trenches 12\"+ from active plant roots. Use between rows, not next to them." },
    ],
    nriTip: "The simplest composting method. No bin, no turning, no monitoring. Dig, dump, cover, forget. The soil does the rest. Perfect for the Return phase when beds are empty.",
  },
] as const;

export type CompostingMethod = (typeof COMPOSTING_METHODS)[number];
