export const CROP_GUIDES: Record<string, CropGuide> = {
  tomato: { name: "Tomato", family: "Solanaceae", season: "warm", daysToHarvest: "60-85", spacingInches: 24, depthInches: 0.25, sunHours: 8, waterNeeds: "moderate", soilPreference: "Well-drained loam, pH 6.0-6.8", companionPlants: ["basil", "carrot", "marigold"], antagonistPlants: ["fennel", "brassicas", "walnut"], commonPests: ["hornworm", "aphids", "flea beetle"], commonDiseases: ["blight", "fusarium wilt", "blossom end rot"], harvestSigns: "Fully colored, slightly soft to squeeze, pulls easily from vine", seedSavingNotes: "Ferment seeds 2-3 days, rinse, dry. Open-pollinated only.", storageNotes: "Never refrigerate — store stem-up at room temperature", nriTip: "Your tomatoes go out after your frost-free date. Start indoors 6-8 weeks before." },
  pepper: { name: "Pepper", family: "Solanaceae", season: "warm", daysToHarvest: "60-90", spacingInches: 18, depthInches: 0.25, sunHours: 8, waterNeeds: "moderate", soilPreference: "Well-drained, pH 6.0-6.8", companionPlants: ["basil", "carrot", "tomato"], antagonistPlants: ["fennel"], commonPests: ["aphids", "pepper weevil"], commonDiseases: ["bacterial spot", "anthracnose"], harvestSigns: "Firm, full-sized, color changed (green→red for most)", seedSavingNotes: "Scrape seeds from ripe fruit, dry 7-10 days. Self-pollinating.", storageNotes: "Refrigerate for 1-2 weeks. Freeze for long-term.", nriTip: "Peppers love heat more than tomatoes. Wait until nights stay above 55°F." },
  lettuce: { name: "Lettuce", family: "Asteraceae", season: "cool", daysToHarvest: "30-60", spacingInches: 8, depthInches: 0.125, sunHours: 4, waterNeeds: "moderate", soilPreference: "Any — very forgiving", companionPlants: ["carrot", "radish", "strawberry"], antagonistPlants: [], commonPests: ["slugs", "aphids"], commonDiseases: ["downy mildew", "tip burn"], harvestSigns: "Outer leaves 4-6\" long for cut-and-come-again, or full heads when firm", seedSavingNotes: "Let one plant bolt. Harvest fluffy seed heads when dry.", storageNotes: "Wash, dry, store in bag with paper towel. 5-7 days.", nriTip: "Lettuce bolts in heat. Succession plant every 2 weeks and grow heat-tolerant varieties in summer." },
  kale: { name: "Kale", family: "Brassicaceae", season: "cool", daysToHarvest: "55-65", spacingInches: 18, depthInches: 0.5, sunHours: 6, waterNeeds: "moderate", soilPreference: "Rich, well-drained, pH 6.0-7.0", companionPlants: ["beet", "celery", "onion"], antagonistPlants: ["strawberry"], commonPests: ["cabbage worm", "aphids", "flea beetle"], commonDiseases: ["clubroot", "black rot"], harvestSigns: "Outer leaves hand-sized. Pick from outside in. Never strip the crown.", seedSavingNotes: "Biennial — overwinter, harvest seed pods year 2. Crosses with all brassicas.", storageNotes: "Refrigerate — lasts 1-2 weeks. Freezes well after blanching.", nriTip: "Frost makes kale sweeter. Plant in late summer for fall harvest — it gets better as temperatures drop." },
  spinach: { name: "Spinach", family: "Amaranthaceae", season: "cool", daysToHarvest: "37-45", spacingInches: 6, depthInches: 0.5, sunHours: 4, waterNeeds: "moderate", soilPreference: "Rich, pH 6.5-7.5", companionPlants: ["pea", "strawberry", "radish"], antagonistPlants: [], commonPests: ["leaf miners", "aphids"], commonDiseases: ["downy mildew"], harvestSigns: "Leaves 3-4\" long. Cut outer leaves or harvest whole plant.", seedSavingNotes: "Dioecious — need male and female plants. Let flower stalks dry.", storageNotes: "Refrigerate in bag — lasts 5-7 days. Freezes well blanched.", nriTip: "Spinach bolts fast in heat. Plant as soon as soil is workable in spring — it handles light frost." },
  carrot: { name: "Carrot", family: "Apiaceae", season: "cool", daysToHarvest: "65-80", spacingInches: 3, depthInches: 0.25, sunHours: 6, waterNeeds: "moderate", soilPreference: "Loose, sandy, rock-free, pH 6.0-6.8", companionPlants: ["onion", "lettuce", "tomato"], antagonistPlants: ["dill"], commonPests: ["carrot rust fly", "aphids"], commonDiseases: ["leaf blight"], harvestSigns: "Tops of root visible at soil surface, shoulders 0.5-0.75\" diameter", seedSavingNotes: "Biennial — needs two years. Leave in ground or store over winter.", storageNotes: "Remove tops. Store in fridge in damp sand — lasts months.", nriTip: "Carrots need loose soil. In clay, grow in raised beds or choose short varieties like Chantenay." },
  radish: { name: "Radish", family: "Brassicaceae", season: "cool", daysToHarvest: "22-30", spacingInches: 2, depthInches: 0.5, sunHours: 6, waterNeeds: "moderate", soilPreference: "Loose, well-drained", companionPlants: ["lettuce", "pea", "carrot"], antagonistPlants: [], commonPests: ["flea beetle", "root maggot"], commonDiseases: ["clubroot"], harvestSigns: "Tops of root pushing above soil, 1\" diameter", seedSavingNotes: "Let a few bolt — seed pods dry on plant. Thresh to release.", storageNotes: "Remove greens. Refrigerate — 2 weeks.", nriTip: "The fastest reward in gardening. Plant radishes with kids — they'll see results before they lose interest." },
  pea: { name: "Pea", family: "Fabaceae", season: "cool", daysToHarvest: "60-70", spacingInches: 3, depthInches: 1, sunHours: 6, waterNeeds: "moderate", soilPreference: "Well-drained, pH 6.0-7.0", companionPlants: ["carrot", "radish", "corn"], antagonistPlants: ["onion", "garlic"], commonPests: ["aphids", "pea weevil"], commonDiseases: ["powdery mildew", "root rot"], harvestSigns: "Pods plump, peas visible through pod. Snap peas: pods fill out.", seedSavingNotes: "Leave pods on vine until brown and rattling. Shell and dry.", storageNotes: "Best eaten immediately. Refrigerate 3-5 days. Freeze well.", nriTip: "Peas fix nitrogen — they feed the soil while feeding you. Plant them where tomatoes will go next." },
  bean: { name: "Bean (Bush)", family: "Fabaceae", season: "warm", daysToHarvest: "50-60", spacingInches: 4, depthInches: 1, sunHours: 6, waterNeeds: "moderate", soilPreference: "Well-drained, pH 6.0-7.0", companionPlants: ["corn", "squash", "carrot"], antagonistPlants: ["onion", "garlic"], commonPests: ["bean beetle", "aphids"], commonDiseases: ["rust", "bacterial blight"], harvestSigns: "Pods snap cleanly, seeds small inside. Pick before pods bulge.", seedSavingNotes: "Leave pods on plant until brown and dry. Shell and store.", storageNotes: "Refrigerate fresh — 5-7 days. Freeze or can for long-term.", nriTip: "Pick beans every 2-3 days to keep plants producing. Once pods mature, the plant stops flowering." },
  zucchini: { name: "Zucchini", family: "Cucurbitaceae", season: "warm", daysToHarvest: "45-55", spacingInches: 36, depthInches: 1, sunHours: 8, waterNeeds: "high", soilPreference: "Rich, well-drained", companionPlants: ["corn", "bean", "nasturtium"], antagonistPlants: ["potato"], commonPests: ["squash bug", "vine borer", "cucumber beetle"], commonDiseases: ["powdery mildew", "blossom end rot"], harvestSigns: "6-8\" long — don't let them get huge. Check daily in peak season.", seedSavingNotes: "Crosses with all C. pepo species. Hand-pollinate for pure seed.", storageNotes: "Refrigerate — 1-2 weeks. Does not freeze well raw.", nriTip: "One zucchini plant produces enough to feed a neighborhood. Seriously — plant fewer than you think you need." },
  garlic: { name: "Garlic", family: "Amaryllidaceae", season: "fall", daysToHarvest: "240 (fall-planted)", spacingInches: 6, depthInches: 2, sunHours: 6, waterNeeds: "low", soilPreference: "Well-drained, pH 6.0-7.0", companionPlants: ["tomato", "pepper", "beet"], antagonistPlants: ["pea", "bean"], commonPests: ["onion maggot"], commonDiseases: ["white rot", "rust"], harvestSigns: "Lower leaves brown, upper still green. Dig — don't pull.", seedSavingNotes: "Save largest cloves from best bulbs for fall planting.", storageNotes: "Cure 2-3 weeks in warm, dry area. Store in mesh bags — lasts 6-8 months.", nriTip: "Plant garlic after your first hard frost in fall. It needs cold to form cloves. Zero effort between planting and harvest." },
  basil: { name: "Basil", family: "Lamiaceae", season: "warm", daysToHarvest: "60-90", spacingInches: 12, depthInches: 0.25, sunHours: 8, waterNeeds: "moderate", soilPreference: "Rich, well-drained", companionPlants: ["tomato", "pepper"], antagonistPlants: [], commonPests: ["aphids", "japanese beetle"], commonDiseases: ["downy mildew", "fusarium wilt"], harvestSigns: "Pinch stems above a leaf pair — plant bushes out. Harvest before flowering.", seedSavingNotes: "Let a few flower stalks dry. Strip tiny black seeds from dried spikes.", storageNotes: "Don't refrigerate — turns black. Stand in water on counter like cut flowers.", nriTip: "Pinch basil above the second set of leaves to make it bush. One plant gives you pesto all summer if you keep pinching." },
};

export interface CropGuide {
  name: string;
  family: string;
  season: "cool" | "warm" | "any" | "fall";
  daysToHarvest: string;
  spacingInches: number;
  depthInches: number;
  sunHours: number;
  waterNeeds: "low" | "moderate" | "high";
  soilPreference: string;
  companionPlants: string[];
  antagonistPlants: string[];
  commonPests: string[];
  commonDiseases: string[];
  harvestSigns: string;
  seedSavingNotes: string;
  storageNotes: string;
  nriTip: string;
}
