export const GARDENING_TECHNIQUES = [
  {
    id: "mulch_layering",
    title: "Mulch Layering",
    category: "mulching" as const,
    philosophies: ["backToEden", "noDig"],
    plain: "Spread 4-6 inches of wood chips or leaves on top of your beds. This smothers weeds, holds moisture, and feeds the soil as it breaks down.",
    gardener: "Apply 4-6\" of arborist wood chips as surface mulch. Avoid volcano-mulching near stems. Replenish annually as it decomposes into humus.",
    source: "Surface mulch reduces evapotranspiration by 25-50%, suppresses weed germination by blocking photosynthetically active radiation, and increases SOM over 2-3 seasons.",
    nriGuidance: "Lead with chip sourcing (ChipDrop, local arborists) before retail. For Back to Eden users, this is the foundation — everything else gets easier after mulch.",
  },
  {
    id: "no_dig_bed_prep",
    title: "No-Dig Bed Prep",
    category: "soil_prep" as const,
    philosophies: ["noDig"],
    plain: "Don't dig. Just pile compost on top of the ground and plant into it. The worms do the mixing for you.",
    gardener: "Layer 4-6\" of finished compost directly on existing soil or lawn. Plant immediately. Top-dress annually. Never invert soil layers.",
    source: "No-dig preserves soil aggregate structure, mycorrhizal hyphal networks, and stratified microbial communities. Dowding trials show equivalent or higher yields vs. tilled controls.",
    nriGuidance: "Never suggest tilling to a No-Dig user. If soil is compacted, suggest broadfork (aeration without inversion) or cardboard-and-compost layering.",
  },
  {
    id: "companion_planting",
    title: "Companion Planting",
    category: "planting" as const,
    philosophies: ["kitchenGarden", "habitatFirst", "homestead"],
    plain: "Some plants help each other when grown nearby. Basil near tomatoes, marigolds near everything. Others fight — keep fennel away from most vegetables.",
    gardener: "Interplant based on pest deterrence, pollinator attraction, and nutrient sharing. Classic combos: tomato+basil, corn+beans+squash (Three Sisters), carrot+onion.",
    source: "Allelopathic interactions, trap cropping (nasturtiums for aphids), nitrogen fixation (legume intercropping), and volatile organic compound-mediated pest deterrence.",
    nriGuidance: "Suggest companions when a user adds crops to their planner. Flag known antagonists (e.g., fennel with most crops, walnut allelopathy).",
  },
  {
    id: "succession_planting",
    title: "Succession Planting",
    category: "planting" as const,
    philosophies: ["kitchenGarden", "homestead"],
    plain: "Plant the same crop every 2-3 weeks so you always have something ready to pick, not everything all at once.",
    gardener: "Stagger sowings of quick crops (lettuce, radish, beans) at 14-21 day intervals. Plan fall successions behind spent spring crops.",
    source: "Succession planting maximizes per-bed yield by maintaining continuous canopy cover and harvest windows. Reduces bolting risk in warm-season lettuce plantings.",
    nriGuidance: "When succession gaps appear in the planner, suggest the next logical crop based on remaining frost-free days and soil temperature.",
  },
  {
    id: "hardening_off",
    title: "Hardening Off Transplants",
    category: "planting" as const,
    philosophies: ["kitchenGarden", "homestead", "communityGarden"],
    plain: "Before planting indoor starts outside, set them out for a few hours each day for a week. They need to get used to wind, sun, and temperature swings.",
    gardener: "Expose transplants to outdoor conditions progressively over 7-10 days. Start with 2-3 hours of filtered light, increase daily. Bring in if frost threatens.",
    source: "Hardening acclimates stomatal response, thickens cuticle wax layer, and upregulates UV-protective flavonoids. Reduces transplant shock mortality from 15-30% to under 5%.",
    nriGuidance: "Trigger hardening reminders 10-14 days before the frost-free date. Use the frost countdown nudge.",
  },
  {
    id: "cover_cropping",
    title: "Cover Cropping",
    category: "soil_prep" as const,
    philosophies: ["homestead", "habitatFirst", "noDig"],
    plain: "Plant clover, rye, or oats in empty beds over winter. They protect the soil, add nutrients, and you chop them down in spring.",
    gardener: "Sow winter rye or crimson clover after fall cleanup. Mow/crimp in spring 2-3 weeks before planting. Legume covers fix 40-200 lbs N/acre.",
    source: "Cover crops reduce erosion, increase water infiltration, break compaction (tillage radish), fix atmospheric N₂ via Rhizobium symbiosis, and suppress overwintering pathogens.",
    nriGuidance: "Suggest cover crops during Preservation and Return phases. Match to soil needs: legumes for N-deficient soils, grasses for erosion-prone slopes.",
  },
  {
    id: "composting_basics",
    title: "Composting Basics",
    category: "soil_prep" as const,
    philosophies: ["backToEden", "noDig", "kitchenGarden", "homestead", "habitatFirst", "communityGarden"],
    plain: "Mix kitchen scraps (greens) with dry leaves or cardboard (browns) in roughly equal amounts. Keep it damp like a wrung-out sponge. Turn it every week or two.",
    gardener: "Maintain 25-30:1 C:N ratio. Greens: food scraps, grass clippings, coffee grounds. Browns: dry leaves, cardboard, straw. Target 130-150°F in hot piles.",
    source: "Thermophilic composting (131-170°F) kills weed seeds and pathogens per EPA 503 standards. Mesophilic composting (ambient) preserves greater microbial diversity but takes 6-12 months.",
    nriGuidance: "Connect to the Compost Tracker. Suggest green/brown additions based on what the user is currently growing and harvesting.",
  },
  {
    id: "vermicomposting",
    title: "Vermicomposting",
    category: "soil_prep" as const,
    philosophies: ["kitchenGarden", "communityGarden"],
    plain: "Red wiggler worms eat your kitchen scraps and turn them into the richest compost on earth. Keep a bin under the sink or in the garage.",
    gardener: "Eisenia fetida in a stacked tray system. Feed 1 lb food scraps per 2 lbs worms per week. Harvest castings every 3-4 months. Avoid citrus, onion, meat.",
    source: "Vermicast contains 5x available N, 7x available P, and 11x available K vs. parent material. Microbial diversity in vermicompost exceeds thermophilic compost.",
    nriGuidance: "Recommend for apartment gardeners, Kitchen Garden users, and anyone with limited outdoor space. Connect to Compost Tracker worm bin type.",
  },
  {
    id: "ipm",
    title: "Integrated Pest Management",
    category: "pest_management" as const,
    philosophies: ["kitchenGarden", "habitatFirst", "homestead"],
    plain: "Before spraying anything, identify the pest, check if it's actually causing damage, and try the gentlest solution first — hand-picking, water spray, or companion plants.",
    gardener: "IPM hierarchy: 1) Prevention (resistant varieties, crop rotation), 2) Cultural (companion planting, sanitation), 3) Mechanical (hand-pick, row covers), 4) Biological (beneficial insects), 5) Chemical (OMRI-listed only, last resort).",
    source: "IPM reduces pesticide use by 50-70% while maintaining yield. Economic injury level (EIL) thresholds guide intervention timing. Beneficial insect habitat increases biological control efficacy.",
    nriGuidance: "Never jump to chemical solutions. When a user reports pests, walk through identification first, then suggest the least-intervention approach that addresses the specific pest.",
  },
  {
    id: "raised_bed_construction",
    title: "Building Raised Beds",
    category: "soil_prep" as const,
    philosophies: ["kitchenGarden", "communityGarden"],
    plain: "A 4x8 foot frame filled with good soil is the easiest way to start. Use untreated wood, fill with a mix of topsoil and compost, and you're planting the same day.",
    gardener: "Cedar or hemlock frames, 10-12\" tall. Fill with 60% topsoil, 30% compost, 10% perlite/vermiculite. Staple hardware cloth underneath if gophers are present.",
    source: "Raised beds warm 2-3 weeks earlier in spring, improve drainage in heavy soils, reduce soil compaction from foot traffic, and enable ergonomic gardening (reduced bending).",
    nriGuidance: "Recommend for clay soils, urban sites, and community gardens. Connect to the Planner's bed dimensions and the Source screen for material sourcing.",
  },
  {
    id: "crop_rotation",
    title: "Crop Rotation",
    category: "crop_rotation" as const,
    philosophies: ["kitchenGarden", "homestead"],
    plain: "Don't plant the same type of vegetable in the same spot two years in a row. Tomatoes, peppers, and eggplant are family — rotate them as a group.",
    gardener: "Rotate by family: Solanaceae → Leguminosae → Brassicaceae → Allium → Cucurbitaceae. 3-4 year rotation breaks pest/disease cycles. Legumes before heavy feeders.",
    source: "Rotation disrupts host-specific pathogen buildup (Verticillium, clubroot, nematodes), balances soil nutrient depletion, and breaks allelopathic autotoxicity cycles.",
    nriGuidance: "Track crop families in the Planner across seasons. Alert when a user places the same family in the same bed as last year.",
  },
  {
    id: "watering_deep",
    title: "Deep Watering",
    category: "watering" as const,
    philosophies: ["backToEden", "kitchenGarden", "homestead"],
    plain: "Water deeply once or twice a week, not a little bit every day. Deep water makes roots grow deep, which makes plants stronger.",
    gardener: "Apply 1-1.5\" per week in one or two sessions. Water at the base, not the leaves. Morning watering reduces disease pressure. Mulch retains 50% more moisture.",
    source: "Infrequent deep irrigation promotes root exploration to 18-24\" depth vs. 4-6\" with frequent shallow watering. Reduces drought vulnerability and improves nutrient access.",
    nriGuidance: "Adjust watering advice based on soil drainage class. Well-drained sandy soils need more frequent watering. Poorly drained clays need less but watch for waterlogging.",
  },
  {
    id: "cold_frame",
    title: "Cold Frame Season Extension",
    category: "season_extension" as const,
    philosophies: ["kitchenGarden", "homestead"],
    plain: "A cold frame is a bottomless box with a glass or plastic lid. It traps heat from the sun and lets you grow greens weeks before and after the normal season.",
    gardener: "Position south-facing, angled 30-45°. Vent when interior exceeds 70°F. Start hardening transplants 4-6 weeks before last frost. Grow fall lettuce into December in Zone 4-5.",
    source: "Cold frames create a microclimate 10-20°F warmer than ambient. Extends growing season 4-8 weeks. Solar gain through glazing provides passive thermal mass heating.",
    nriGuidance: "Suggest during Preparation and Return phases for season extension. Connect to frost countdown nudges.",
  },
  {
    id: "row_cover",
    title: "Row Cover Protection",
    category: "season_extension" as const,
    philosophies: ["kitchenGarden", "homestead"],
    plain: "Lightweight fabric draped over plants keeps frost off and bugs out. It lets light and rain through. The best $15 you'll spend in the garden.",
    gardener: "Floating row cover (Agribon AG-19) provides 4°F frost protection. Use hoops to prevent leaf contact. Remove for pollination of fruiting crops. AG-30 for heavier frost.",
    source: "Spunbond polypropylene row covers transmit 85-95% PAR while providing 2-8°F frost protection depending on weight. Also excludes flea beetles, cabbage moths, and carrot rust fly.",
    nriGuidance: "Recommend when frost alerts fire. Specifically mention which crops in the user's beds are frost-sensitive and need covering.",
  },
  {
    id: "soil_testing",
    title: "Soil Testing",
    category: "soil_prep" as const,
    philosophies: ["kitchenGarden", "homestead", "noDig"],
    plain: "A $15 soil test from your extension office tells you exactly what your soil needs — no guessing. Do it once a year, ideally in fall.",
    gardener: "Submit samples to your state extension lab for pH, NPK, organic matter, and CEC. Follow their specific amendment recommendations. Retest annually for the first 3 years.",
    source: "Extension soil tests use Mehlich-3 extraction for P/K/micronutrients, pH by 1:1 water method, loss-on-ignition for SOM, and ammonium acetate for CEC. Cost: $10-25.",
    nriGuidance: "When SSURGO data is available, compare lab results against the federal data. Note discrepancies — they usually mean the user's management has improved (or degraded) their soil.",
  },
  {
    id: "ph_adjustment",
    title: "Adjusting Soil pH",
    category: "soil_prep" as const,
    philosophies: ["kitchenGarden", "homestead"],
    plain: "Most vegetables like soil between 6.0 and 7.0. Too acidic? Add lime. Too alkaline? Add sulfur. A soil test tells you which and how much.",
    gardener: "Apply pelletized lime at 5 lbs/100sqft to raise pH by ~0.5. Elemental sulfur at 1 lb/100sqft to lower. Work into top 6\". Retest after 3 months.",
    source: "Soil pH governs nutrient cation/anion availability. Below 5.5: Al/Mn toxicity risk. Above 7.5: Fe/Zn/Mn deficiency. Buffer pH (SMP method) determines lime requirement more accurately than water pH alone.",
    nriGuidance: "Reference the user's SSURGO pH data. If pH is 6.0-7.0, say it's fine. Only suggest amendments if clearly outside range. Never recommend amending without a soil test.",
  },
] as const;

export type GardeningTechnique = (typeof GARDENING_TECHNIQUES)[number];
