export const SEED_SAVING_GUIDES = [
  {
    id: "tomato", cropName: "Tomato", difficulty: "beginner" as const,
    pollinationType: "self" as const, isolationDistance: "10-25 ft (varieties can cross via insects)",
    harvestMethod: "Pick fully ripe fruit, scoop seeds into a jar",
    processingMethod: "wet_ferment" as const, storageLife: "4-6 years",
    steps: ["Select best-tasting, disease-free fruits from strongest plant", "Scoop seeds and gel into a jar with a little water", "Ferment 2-3 days at room temperature until mold forms on surface", "Rinse seeds thoroughly — viable seeds sink, duds float", "Dry on a plate (not paper towel — they stick) for 5-7 days", "Store in labeled envelope in cool, dry place"],
    nriTip: "Tomato seed saving is the perfect first project. The fermentation step mimics what happens naturally in a fallen fruit. Brandywine, Cherokee Purple, and San Marzano are all open-pollinated — hybrids won't come true from saved seed.",
  },
  {
    id: "pepper", cropName: "Pepper", difficulty: "beginner" as const,
    pollinationType: "self" as const, isolationDistance: "50 ft (insects can cross-pollinate)",
    harvestMethod: "Let fruit fully ripen (red/orange), scrape seeds from placenta",
    processingMethod: "dry" as const, storageLife: "2-4 years",
    steps: ["Let peppers ripen fully on the plant — past eating stage", "Cut open and scrape seeds from the white membrane", "Spread on plate to dry for 7-10 days", "Seeds should snap when bent, not bend", "Store in labeled envelope"],
    nriTip: "Pepper seeds are easier than tomato — no fermentation needed. Just let the fruit get fully red (or whatever its mature color is) and dry the seeds. Wear gloves for hot peppers.",
  },
  {
    id: "lettuce", cropName: "Lettuce", difficulty: "beginner" as const,
    pollinationType: "self" as const, isolationDistance: "10 ft (rarely crosses)",
    harvestMethod: "Let one plant bolt and flower. Harvest seed heads when fluffy.",
    processingMethod: "dry" as const, storageLife: "3-5 years",
    steps: ["Let one lettuce plant bolt (go to flower) — don't harvest it", "Wait for yellow flowers to appear, then small dandelion-like puffs", "When seed heads are dry and fluffy, cut the stalk", "Place upside down in a paper bag for 1-2 weeks", "Shake bag to release seeds. Winnow chaff outdoors"],
    nriTip: "Lettuce seeds itself so easily it's almost a weed. Let one plant bolt each season and you'll never buy lettuce seed again. Each plant produces hundreds of seeds.",
  },
  {
    id: "pea", cropName: "Pea", difficulty: "beginner" as const,
    pollinationType: "self" as const, isolationDistance: "10 ft",
    harvestMethod: "Leave pods on vine until brown and dry. Harvest when pods rattle.",
    processingMethod: "dry" as const, storageLife: "3 years",
    steps: ["Mark your best, most productive plants early in the season", "Stop harvesting those plants — let ALL pods mature", "Leave on vine until pods are brown, dry, and papery", "Pick pods when they rattle when shaken", "Shell peas from pods. Spread to dry 1 week", "Store in envelope — they're ready to plant next year"],
    nriTip: "Peas are the easiest seed to save. The seeds ARE the peas — just dried. Every pea you don't eat is a seed for next year. Leave 5-10 pods on your best plant.",
  },
  {
    id: "bean", cropName: "Bean", difficulty: "beginner" as const,
    pollinationType: "self" as const, isolationDistance: "10-20 ft",
    harvestMethod: "Leave pods on plant until completely dry and brown.",
    processingMethod: "dry" as const, storageLife: "3-4 years",
    steps: ["Let pods dry completely on the plant — they should be brown and papery", "Pick dry pods before they split and drop seeds", "If weather threatens, pull whole plant and hang upside down indoors", "Shell beans from pods", "Spread on screen for 1-2 weeks to ensure fully dry", "Store in glass jar with silica packet"],
    nriTip: "Bean saving is almost identical to pea saving. The oldest seed-saving tradition in the Americas — Three Sisters gardens have been saving bean seed for thousands of years.",
  },
  {
    id: "squash", cropName: "Squash / Pumpkin", difficulty: "intermediate" as const,
    pollinationType: "insect" as const, isolationDistance: "0.5 mile (or hand-pollinate)",
    harvestMethod: "Scoop seeds from fully ripe fruit, wash and dry.",
    processingMethod: "dry" as const, storageLife: "4-6 years",
    steps: ["IMPORTANT: Only save from open-pollinated varieties, not hybrids", "Squash species cross freely — isolate by species or hand-pollinate", "Let fruit mature fully on vine (past eating stage for summer squash)", "Scoop seeds, rinse clean of pulp in a colander", "Spread on plate to dry for 1-2 weeks", "Seeds should snap cleanly when bent"],
    nriTip: "Squash crossing is the #1 seed saving surprise. A zucchini near a pumpkin will cross — next year's seeds grow something weird. Hand-pollinate or grow only one variety per species.",
  },
  {
    id: "cucumber", cropName: "Cucumber", difficulty: "intermediate" as const,
    pollinationType: "insect" as const, isolationDistance: "0.5 mile (or hand-pollinate)",
    harvestMethod: "Let fruit over-ripen on vine until yellow/orange, scoop and ferment seeds.",
    processingMethod: "wet_ferment" as const, storageLife: "5-10 years",
    steps: ["Leave 1-2 cucumbers on the vine way past eating stage — they turn yellow/orange", "Scoop seeds and gel into jar with water", "Ferment 1-2 days (shorter than tomato)", "Rinse — viable seeds sink", "Dry on plate for 1 week"],
    nriTip: "Cucumber seeds last a decade or more — among the longest-lived vegetable seeds. One over-ripe cucumber gives you enough seed for years.",
  },
  {
    id: "basil", cropName: "Basil", difficulty: "beginner" as const,
    pollinationType: "insect" as const, isolationDistance: "150 ft between varieties",
    harvestMethod: "Let flower spikes dry on plant, then strip seeds.",
    processingMethod: "dry" as const, storageLife: "5 years",
    steps: ["Let a few stems flower (stop pinching those stems)", "Wait for flower spikes to dry and turn brown on the plant", "Cut spikes and place upside down in paper bag", "Shake — tiny black seeds fall out", "Sift to remove chaff"],
    nriTip: "Basil produces prolific seed. One flowering stem gives you hundreds. Let 2-3 stems flower at season end while continuing to harvest from the rest of the plant.",
  },
  {
    id: "sunflower", cropName: "Sunflower", difficulty: "beginner" as const,
    pollinationType: "insect" as const, isolationDistance: "0.5 mile for pure seed",
    harvestMethod: "Cut head when back turns brown, dry indoors, rub seeds loose.",
    processingMethod: "dry" as const, storageLife: "5-7 years",
    steps: ["Wait for petals to fall and back of head to turn brown", "Cut head with 12\" of stem attached", "Hang upside down in dry, ventilated area for 2 weeks", "Rub seeds loose over a bucket", "Dry an additional week spread on screen", "Store in sealed container"],
    nriTip: "Sunflower seeds are the most rewarding to save — big, visible, and kids love helping. Cover heads with mesh bags if birds start eating them before you harvest.",
  },
  {
    id: "kale", cropName: "Kale", difficulty: "intermediate" as const,
    pollinationType: "insect" as const, isolationDistance: "0.5 mile (crosses with broccoli, cabbage, cauliflower)",
    harvestMethod: "Biennial — overwinter plant, harvest seed pods in second year.",
    processingMethod: "thresh" as const, storageLife: "4-5 years",
    steps: ["Kale is biennial — it flowers in its second year", "Overwinter your best plant (mulch crown in cold climates)", "In spring of year 2, let it flower and form seed pods", "Wait until pods turn brown and dry", "Cut stalks, dry in paper bag 2 weeks", "Thresh pods to release seeds (step on bag or roll with rolling pin)"],
    nriTip: "Kale seed saving requires patience — it's a two-year commitment. But one plant produces enough seed for an entire community garden. All brassicas cross, so grow only one variety for seed.",
  },
] as const;

export type SeedSavingGuide = (typeof SEED_SAVING_GUIDES)[number];
