export const SOIL_SCIENCE = [
  {
    id: "texture_triangle",
    topic: "Soil Texture Triangle",
    plain: "Soil is made of three particle sizes: sand (big, gritty), silt (medium, silky), and clay (tiny, sticky). Your soil's mix of these three determines how it holds water, drains, and grows roots.",
    gardener: "The USDA texture triangle classifies soil by % sand, silt, and clay. Loam (40-40-20) is ideal. Sandy soils drain fast but dry out. Clay holds water but compacts. Know your texture to choose amendments wisely.",
    source: "USDA soil texture classes derived from particle size distribution: sand (0.05-2mm), silt (0.002-0.05mm), clay (<0.002mm). Textural class determines hydraulic conductivity, available water capacity, and cation exchange capacity.",
    relatedFields: ["texture"],
    actionableAdvice: "Grab a handful of damp soil and squeeze. Sandy crumbles immediately. Clay ribbons between your fingers. Loam holds shape then breaks apart. This 30-second test tells you more than most gadgets.",
  },
  {
    id: "drainage_classes",
    topic: "Drainage Classes (A-D)",
    plain: "How fast water disappears after rain tells you your drainage class. Fast drainage (A) means sandy soil that dries quickly. Slow drainage (D) means clay that puddles for hours.",
    gardener: "Hydrologic soil groups: A (sand/gravel, >1.5\"/hr infiltration), B (loam, 0.6-1.5\"/hr), C (clay loam, 0.2-0.6\"/hr), D (heavy clay, <0.2\"/hr). Most vegetables prefer A-B. Heavy clay benefits from raised beds.",
    source: "NRCS Hydrologic Soil Groups (HSG) classify runoff potential. Group A: low runoff, high infiltration. Group D: high runoff, very slow infiltration. Dual groups (A/D, B/D) indicate seasonal high water table influence.",
    relatedFields: ["drainage"],
    actionableAdvice: "After a good rain, check your yard at 1 hour and 4 hours. Puddles gone in an hour? You're A or B. Still standing at 4 hours? You're C or D. Build up, don't dig down.",
  },
  {
    id: "ph_nutrients",
    topic: "pH and Nutrient Availability",
    plain: "Soil pH is like a lock on your nutrients. If pH is too high or too low, plants can't access the food that's already in the soil. Most vegetables want pH between 6.0 and 7.0.",
    gardener: "Nutrient availability peaks at pH 6.0-7.0 for most macronutrients. Below 5.5, aluminum and manganese become toxic. Above 7.5, iron, zinc, and manganese get locked up. Blueberries are the exception — they want 4.5-5.5.",
    source: "Soil pH governs speciation and solubility of nutrient cations and anions. Phosphorus availability peaks at pH 6.0-7.0 (minimum Al/Fe-P and Ca-P precipitation). Micronutrient availability (Fe, Mn, Zn, Cu) decreases above pH 7.0.",
    relatedFields: ["pH"],
    actionableAdvice: "A $10 pH test kit from any garden center gives you the answer in 5 minutes. If you're between 6.0 and 7.0, stop worrying about pH and focus on organic matter instead.",
  },
  {
    id: "organic_matter",
    topic: "Organic Matter and Soil Life",
    plain: "The life in your soil — bacteria, fungi, earthworms, insects — is what makes plants grow. More organic matter means more life. Compost, mulch, and cover crops are how you feed it.",
    gardener: "Target 3-5% SOM for productive vegetable gardens. Each 1% increase improves water-holding capacity by ~20,000 gallons/acre. Build SOM through annual compost application, mulching, and minimal tillage.",
    source: "Soil organic matter (SOM) serves as nutrient reservoir (CEC contribution), water retention matrix (AWC correlation), aggregate stabilizer (glomalin binding), and energy source for soil food web. SOM decomposition rate governed by C:N ratio, temperature, moisture, and O₂ availability.",
    relatedFields: ["organicMatter"],
    actionableAdvice: "Dark soil usually has more organic matter. If your soil is pale and dusty, start adding compost. Two inches on top every spring will transform it within 3 years.",
  },
  {
    id: "nitrogen_cycle",
    topic: "The Nitrogen Cycle",
    plain: "Plants need nitrogen to grow leaves. It comes from compost, manure, legume roots (beans and peas), and slowly from decomposing mulch. You almost never need to buy nitrogen fertilizer if you compost.",
    gardener: "Nitrogen cycles: atmospheric N₂ → biological fixation (Rhizobium in legume nodules) → ammonium (NH₄⁺) → nitrification to nitrate (NO₃⁻) → plant uptake. Compost provides slow-release N. Fresh wood chips temporarily tie up N at the soil surface.",
    source: "Biological nitrogen fixation by Rhizobium spp. in legume symbiosis contributes 40-200 lbs N/acre/year. Mineralization of SOM releases ~20 lbs N/acre per 1% SOM annually. C:N ratio >25:1 causes net N immobilization.",
    relatedFields: ["organicMatter"],
    actionableAdvice: "Grow beans or peas every year. Their roots add nitrogen that the next crop uses. Follow legumes with heavy feeders like tomatoes or corn. Nature's fertilizer is free.",
  },
  {
    id: "soil_compaction",
    topic: "Soil Compaction",
    plain: "Walking on garden soil squishes out the air spaces that roots and water need. Stay on paths, never walk on beds, and mulch to protect the surface.",
    gardener: "Compaction increases bulk density, reduces macropore volume, and restricts root penetration. Remediate with broadfork (no-dig compatible), cover crop roots (tillage radish), or permanent raised beds with dedicated pathways.",
    source: "Bulk density >1.6 g/cm³ in loam restricts root growth. Compaction reduces saturated hydraulic conductivity by orders of magnitude. Biological decompaction via root channels (bio-drilling) is preferred over mechanical tillage.",
    relatedFields: ["workability"],
    actionableAdvice: "Can you push a stick into your soil easily? If it stops at 6 inches, you have compaction. A broadfork loosens soil without flipping it — 20 minutes per bed, once a year.",
  },
  {
    id: "mycorrhizal_fungi",
    topic: "Mycorrhizal Fungi",
    plain: "Underground fungal networks connect to plant roots and help them absorb water and nutrients from much farther away than roots alone could reach. Tilling destroys these networks.",
    gardener: "Arbuscular mycorrhizal fungi (AMF) extend the effective root zone 10-100x. They trade phosphorus and micronutrients for plant sugars. Maintain by avoiding tillage, reducing synthetic fertilizer, and keeping living roots in soil year-round.",
    source: "AMF colonize >80% of plant species. Hyphal networks increase P uptake 3-5x, improve drought resistance via hydraulic redistribution, and enhance soil aggregation through glomalin production. Disrupted by tillage, high P fertilization, and fallow periods.",
    relatedFields: ["organicMatter", "workability"],
    actionableAdvice: "The best thing you can do for soil fungi is stop disturbing them. No-dig, mulch, and keep roots in the ground year-round (cover crops). The fungi do the rest.",
  },
  {
    id: "frost_heaving",
    topic: "Frost Heaving",
    plain: "In cold climates, soil freezes and expands, which can push plants and their roots right out of the ground. A thick mulch layer insulates against this.",
    gardener: "Frost heaving occurs in fine-textured soils (silt, clay) when ice lenses form and expand. Mulch 4-6\" of straw or leaves over perennial crowns and newly planted garlic before ground freezes. Firm plants back if heaved.",
    source: "Frost heave driven by capillary rise feeding ice lens growth at the freezing front. Silt loams most susceptible (high capillarity, moderate permeability). Heave pressure can exceed 150 psi, sufficient to lift foundations.",
    relatedFields: ["texture", "depth"],
    actionableAdvice: "Mulch your perennials before the first hard freeze. Garlic, strawberries, and newly planted perennials are most vulnerable. 4-6 inches of straw or leaves does the job.",
  },
] as const;

export type SoilScienceEntry = (typeof SOIL_SCIENCE)[number];
